Updated release

diff --git a/.github/workflows/release-versa-wasm.yml b/.github/workflows/release-versa-wasm.yml
--- a/.github/workflows/release-versa-wasm.yml
+++ b/.github/workflows/release-versa-wasm.yml
@@ -2,16 +2,6 @@ name: Build and Release versa-wasm
 
 on:
   workflow_dispatch:
-    inputs:
-      major:
-        description: "Major Version"
-        required: true
-      minor:
-        description: "Minor Version"
-        required: true
-      patch:
-        description: "Patch Version"
-        required: true
 
 jobs:
   build-and-release-wasm:
@@ -19,12 +9,14 @@ jobs:
     strategy:
       matrix:
         include:
-          - os: ubuntu-latest
-            target: x86_64-unknown-linux-musl
+          # - os: ubuntu-latest
+          #   target: x86_64-unknown-linux-musl
+          # - os: ubuntu-latest
+          #   target: x86_64-unknown-freebsd
           # - os: ubuntu-latest
           #   target: aarch64-unknown-linux-musl
-          # - os: macos-latest
-          #   target: x86_64-apple-darwin
+          - os: macos-latest
+            target: x86_64-apple-darwin
           # - os: macos-latest
           #   target: aarch64-apple-darwin
           # - os: windows-latest
@@ -35,6 +27,12 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@v2
 
+      # - name: Check tag
+      #   if: ${{ !inputs.tag || inputs.tag == 'latest' }}
+      #   run: |
+      #     echo "::error::You may not publish the 'latest' tag using this workflow."
+      #     exit 1
+
       - name: Set up Cross-Compilation for aarch64-linux-musl
         if: matrix.target == 'aarch64-unknown-linux-musl'
         run: |
@@ -42,14 +40,6 @@ jobs:
           sudo apt-get install -y musl-tools
           echo "[target.aarch64-unknown-linux-musl]" >> ~/.cargo/config
           echo "linker = 'aarch64-linux-musl-gcc'" >> ~/.cargo/config
-
-      - name: Install musl-tools for x86_64-unknown-linux-musl
-        if: matrix.target == 'x86_64-unknown-linux-musl'
-        run: sudo apt-get install musl-tools
-
-      - name: Configure Environment for musl Target
-        if: matrix.target == 'x86_64-unknown-linux-musl'
-        run: |
           echo "CC_x86_64-unknown-linux-musl=musl-gcc" >> $GITHUB_ENV
 
       - name: Set up Rust
@@ -65,25 +55,33 @@ jobs:
           cd crates/wasm_cli
           cargo build --release --target ${{ matrix.target }}
 
-      - name: Create Release (runs only once)
-        if: github.event.inputs.major && github.event.inputs.minor && github.event.inputs.patch && matrix.target == 'x86_64-unknown-linux-gnu'
-        id: create_release
-        uses: actions/create-release@v1
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Release
+        uses: softprops/action-gh-release@v1
+        # if: startsWith(github.ref, 'refs/tags/')
         with:
-          tag_name: ${{ github.event.inputs.major }}.${{ github.event.inputs.minor }}.${{ github.event.inputs.patch }}
-          release_name: Release v${{ github.event.inputs.major }}.${{ github.event.inputs.minor }}.${{ github.event.inputs.patch }}
-          draft: true
-          prerelease: true
+          files: |
+            ./target/${{ matrix.target }}/release/versa-wasm
+      # - name: Create Release (runs only once)
+      #   if: github.event.inputs.tag != 'edge' && matrix.target == 'x86_64-unknown-linux-musl'
+      #   id: create_release
+      #   uses: actions/create-release@v1
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      #   with:
+      #     tag_name: ${{ github.event.inputs.tag }}
+      #     release_name: Release ${{ github.event.inputs.tag }}
+      #     draft: false
+      #     prerelease: false
 
-      - name: Upload Release Asset
-        if: steps.create_release.outputs.upload_url
-        uses: actions/upload-release-asset@v1
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          upload_url: ${{ steps.create_release.outputs.upload_url }}
-          asset_path: ./target/${{ matrix.target }}/release/versa-wasm
-          asset_name: versa-wasm-${{ matrix.target }}
-          asset_content_type: application/octet-stream
+      # - name: Upload Release Asset
+      #   if: steps.create_release.outputs.upload_url
+      #   uses: actions/upload-release-asset@v1
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      #   with:
+      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
+      #     asset_path: ./target/${{ matrix.target }}/release/versa-wasm
+      #     asset_name: versa-wasm-${{ matrix.target }}.tar.gz
+      #     asset_content_type: application/octet-stream
+      #   run: |
+      #     tar -czvf versa-wasm-${{ matrix.target }}.tar.gz -C ./target/${{ matrix.target }}/release versa-wasm
